export enum SbBetLegType {
  HOME_SPREAD = "HOME_SPREAD",
  AWAY_SPREAD = "AWAY_SPREAD",
  HOME_MONEYLINE = "HOME_MONEYLINE",
  AWAY_MONEYLINE = "AWAY_MONEYLINE",
  OVER_TOTAL = "OVER_TOTAL",
  UNDER_TOTAL = "UNDER_TOTAL",
}
